### ISSUE TITLE
Move vue to be a dev dependency in package.json

### ISSUE THREAD

**Issue by Mike-Gibson-Advanced** [hjkcai/vue-modal-dialogs#1]
Firstly, thanks for creating vue-modal-dialogs - it's a nice library to use. I noticed that I receive TypeScript compilation errors when using a version of vue different to the one specified in the package.json file.

I believe that the vue dependency should be  moved to the devDependencies section and the TypeScript definition file should be updated. You can see how vue-router do it:
[in package.json](https://github.com/vuejs/vue-router/blob/b9bbde6ec160d839bcbb80466a862adc1fbe803f/package.json#L73) and [in the definition file](https://github.com/vuejs/vue-router/blob/b9bbde6ec160d839bcbb80466a862adc1fbe803f/types/router.d.ts#L1)

This means when installing vue-modal-dialogs it won't pull in a new version of vue, and the TypeScript compiler will use the typings of whatever version of vue is installed in the project.

Happy to create a PR if you are OK with the suggestion.

**Comment by hjkcai** [comment]
Thanks for helping me so much with my project! TypeScript definitions and some other functionalities are not being tested because I am quite busy these days. And I am new to creating packages on npm. I am really sorry for that. Feel free to send me a PR with your suggestions 😁😁😁. I will test for that later.

**Comment by hjkcai** [comment]
I have moved `vue` into `peerDependencies`, `babel-preset-env` into `devDependencies`, and removed `element-ui` in the dependencies. You can now install `vue-modal-dialogs@1.1.2` from npm.
