### ISSUE TITLE
Fails on IE and minified vue

### ISSUE THREAD

**Issue by ppn2** [hjkcai/vue-modal-dialogs#10]
Following code fails on IE. The reason is that IE does not support function.name property. Also this fails, when one uses minified version of vue, because minifier rewrites the "VueComponent" function.
```
export function isVueComponent (obj) {
  return (
    obj != null &&
    (typeof obj === 'object' || typeof obj === 'function')
  ) && (
    // must not a Vue instance
    Object.getPrototypeOf(obj).constructor.name !== 'VueComponent'
  ) && (
    // result of Vue.extend
    (typeof obj === 'function' && obj.name === 'VueComponent') ||

    // import from a .vue file
    Array.isArray(obj.staticRenderFns) ||

    // has a render function
    typeof obj.render === 'function'
  )
}
```

I would suggest that you use following code.
```
import VueComponent from "vue";
.
.
.
export function isVueComponent (obj) {
  return obj && obj.super == VueComponent;
}
```

**Comment by hjkcai** [comment]
I have removed `isVueComponent` check in the further version. So far you may install an alternative version of vue-modal-dialogs called `vue-modal-dialogs-ts`. Sorry for your inconvenient. I will inform you when the new version is ready.

**Comment by hjkcai** [comment]
I released vue-modal-dialogs 2.0.0 just now. The function `isVueComponent` is not fully removed but is tested in production (only chrome so far). Try it out!

**Comment by ppn2** [comment]
@hjkcai I tried the new code. Works beautifully. One thing this is missing is that the $close function does not return anything, which is not a problem if there are no animation. However when there are animations, I would like the $close to return a promise, which resolves when the animation is complete.

**Comment by hjkcai** [comment]
$close function returns the original Promise. But this function is not
designed to wait until the transition ends. This is a grate suggestion. I
will try to implement it.


On 19 December 2017 at 3:41:15 AM, ppn2 (notifications@github.com) wrote:

@hjkcai <https://github.com/hjkcai> I tried the new code. Works
beautifully. One thing this is missing is that the $close function does not
return anything, which is not a problem if there are no animation. However
when there are animations, I would like the $close to return a promise,
which resolves when the animation is complete.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hjkcai/vue-modal-dialogs/issues/10#issuecomment-352536332>,
or mute the thread

**Comment by ppn2** [comment]
@hjkcai Yes you are right and thanks for looking forward to implement the wait till transition ends. I do have one more suggestion.

This is related to the scrolling behavior of the page. basically when there is a scrollbar on the page and the dialog opens, the user can still scroll up and down, which makes it weird as the dialog stays fixed and the background page moves. To fix that we generally put a style on the body "overflow: hidden" when the dialog is open and remove this style when the dialog is closed (preferably using css class). the overvlow:hidden causes the scrollbar to disappear and that way scrolling is disabled while dialog is open.

However this creates a new problem. when scrollbar disappears, the content of the host page re-flow (if the page is responsive). To fix this problem, we add another style margin-right: 17px and that way the page content do not reflow. However that also have another problem. the scrollbar width is different in different browser, the the right margin needs to be determine at run time.

There are two ways to approach this problem. 
1. You can put all this logic the vue-dialog-component.
2. Create two global hooks which are fired when the dialog is opened and dialog is closed and developer can take care of scrolling needs.

I hope this makes sense. Let me know if I am not clear on this.

**Comment by hjkcai** [comment]
The core concept of vue-modal-dialogs it to help developers code easier in these tedious dialogs scenarios.  Features involving controlling CSS styles will not be added.   You have to lock the scroll bar by yourself. 

Locking the scroll bar is not as simple as setting overflow property on body element. It depends on how you layout your page. So it is not a good idea to add this feature. 

The events on opening and closing dialogs are planned in the next release (maybe next week). So far you can use events of transition-group to get the similar feature. 

BTW, could you please open another two issues about the two features you have requested? It is easier to let other people involve the discussion.

Thanks for your suggestions.
