### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by ismile** [hjkcai/vue-modal-dialogs#11]
Hi @hjkcai, I get this error when trying importing this plugin.

I looked into node_modules directory and the code still use es6 import, it seem.... it doesn't compile correctly?

for now I copied this plugin manually into my project folder and make webpack compiled it. this way the plugin work flawless. anyway I love your plugin.

**Comment by hjkcai** [comment]
Hey!

In fact, these files are already compiled from ES6 to ES5 with only `import` preserved. This module is meant to use together with module bundlers like webpack (>=2.0.0) or rollup. They have built in ES module resolving logic. This will help decrease the size of this module. 

If you use the official project template from Vue, you are able to use this module directly. I guess you are using an old version of webpack with babel to transform the ES6 import statements. You have several options:

1. Copy everything into your project just like what you have done
2. Clone this repo, setup webpack or rollup and make a commonjs build
3. Configure webpack and babel to transform things inside `node_modules/vue-model-dialogs`

I am glad to hear that you love this module! Please let me know if you have other questions.

**Comment by ismile** [comment]
thanks for clear it up, anyway I use it inside nuxtjs... it seem by default nuxtjs ignoring node_madules path.

the first option that what I've done... was temporary fix, I will try to figure out how to extend webpack config inside nuxtjs and include this module.

again... thanks

**Comment by hjkcai** [comment]
You're welcome! But... theoretically nuxt.js is based on Vue and webpack. I think it should work correctly. I think i should test on it later.
