### ISSUE TITLE
Integrating it to bootstrap 4 modal UI

### ISSUE THREAD

**Issue by Abenezer** [hjkcai/vue-modal-dialogs#12]
boot strap 4 users data-toggle to activate the modal that's is not shown by default 
`<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>`
how would you fire toggle on makeDialog activate this toggle on click
i have messageDialog component with bootstrap modal 
`<template><div><div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"><div class="modal-dialog" role="document"></div></template>`

**Comment by hjkcai** [comment]
According to [Bootstrap's doc](https://getbootstrap.com/docs/4.0/components/modal/#via-javascript), you need the following steps:

1. Remove `data-toggle` attribute on the button
2. Remove the out-most `<div>` element
3. Tell bootstrap to show the dialog and listen to its `hide.bs.modal` event when the dialog component is mounted

Your dialog component will look like this:

```html
<template>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">...</div>
    </div>
  </div>
</template>

<script>
  export default {
    mounted () {
      $(this.$el).modal('show')
      $(this.$el).on('hide.bs.modal', this.$close)
    }
  }
</script>
```

This should be work as expected.
