### ISSUE TITLE
How to add dialogs-wrapper to my app.js in Vue?

### ISSUE THREAD

**Issue by BennieBe** [hjkcai/vue-modal-dialogs#13]
When I try to add the dialogs wrapper into my files, it does not register properly. I am getting this error message: 
Unknown custom element: <dialogs-wrapper> - did you register the component correctly? For recursive components, make sure to provide the "name" option
I added <dialogs-wrapper name="default"></dialogs-wrapper> to my app.js, which does not work.
What am I missing?

**Comment by hjkcai** [comment]
Hello. Could you please show me your code? I guess you forgot `Vue.use(ModalDialogs)`.

**Comment by monkeymonk** [comment]
Same problem here. I have `Vue.use(ModalDialogs)` in my code. Do we have to add the component in our code ? I see nothing about that in the docs.

**Comment by hjkcai** [comment]
@monkeymonk No, that is enough. The lib will register for you
