### ISSUE TITLE
no demo project !!! it's hard to implement. please add one Vue demo project ...

### ISSUE THREAD

**Issue by Peraluna** [hjkcai/vue-modal-dialogs#17]
Please add demo project ..... the documentation is not clear enough for quick look at the functionalities

**Comment by hjkcai** [comment]
Hello, you gotta understand the key word **promisify**. It means turning async procedures into a JavaScript `Promise` for easier further use with the async function. Try to learn about `Promise` and async function before getting started with vue-modal-dialogs.

Here is the guide and demo: https://hjkcai.github.io/vue-modal-dialogs

Here is the demo project: https://github.com/hjkcai/vue-modal-dialogs/tree/examples
