### ISSUE TITLE
Issue with Object.assign in IE11

### ISSUE THREAD

**Issue by joachimVT** [hjkcai/vue-modal-dialogs#18]
IE11 complains about the missing Object.assign even though babel-polyfill are imported the top of the app.

```
"devDependencies": {
    "axios": "^0.18",
    "cross-env": "^5.1",
    "laravel-mix": "^2.1",
    "laravel-mix-purgecss": "^2.2.3",
    "laravel-mix-tailwind": "^0.1.0",
    "lodash": "^4.17.11",
    "tailwindcss": "^0.6.6",
    "vue": "^2.5.17"
},
"dependencies": {
    "babel-polyfill": "^6.26.0",
    "laravel-echo": "^1.4.0",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.17",
    "pusher-js": "^4.3.0",
    "vue-modal-dialogs": "^3.0.0",
    "vue-template-compiler": "^2.5.17"
}
```

How could this be fixed ?

**Comment by hjkcai** [comment]
Polyfills do not automatically work with codes inside the `node_modules` folder. But you can manually import the polyfill:

1. install `core-js` (maybe it is included in the `babel-polyfill` package. I am not sure) 
2. insert this into your very first line of code:

```javascript
import 'core-js/es/object/assign'
```

**Comment by joachimVT** [comment]
Thanks for the info , I ended up loading core-js and adding 

`import 'core-js/es6/object'`

This fixed it for me
