### ISSUE TITLE
dialog not show up

### ISSUE THREAD

**Issue by Frankie34** [hjkcai/vue-modal-dialogs#19]
[my-project.zip](https://github.com/hjkcai/vue-modal-dialogs/files/2785542/my-project.zip)

Hi, here is a newbee to Vue.js

I follow the instruction at https://hjkcai.github.io/vue-modal-dialogs/ but the dialog didn't show up as expected.

HELP!

main.js
import Vue from 'vue'
import App from './App'
import Element from 'element-ui'
import * as ModalDialogs from 'vue-modal-dialogs'

Vue.config.productionTip = false
Vue.use(ModalDialogs)
Vue.use(Element)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  render: h => h(App)
})

App.vue
<template>
  <div id="app">
    <div>
    <helloworld></helloworld>
    </div>
    <dialogs-wrapper></dialogs-wrapper>
  </div>
</template>

<script>
import helloworld from './components/helloWorld'

export default {
  name: 'App',
  components: {
    helloworld
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

**Comment by Frankie34** [comment]
the <dialog-wrapper> seems not work as expected

**Comment by hjkcai** [comment]
@Frankie34 从你发的文件里面来看，是因为 src/components/helloWorld.vue 的结尾没有 `</script>` 导致 vue-loader 解析失败，所以 helloWorld 整个组件都挂了。补上 `</script>` 后就都正常了

**Comment by hjkcai** [comment]
@MicroDreamIT Could you please provide some more information about the problem occurred? BTW please submit a new issue 😄

**Comment by MicroDreamIT** [comment]
sure bro. I will

**Comment by Frankie34** [comment]
> @Frankie34 从你发的文件里面来看，是因为 src/components/helloWorld.vue 的结尾没有 `</script>` 导致 vue-loader 解析失败，所以 helloWorld 整个组件都挂了。补上 `</script>` 后就都正常了

非常感谢Orz当时疏忽了，想猛烈地敲打自己

**Comment by paulm17** [comment]
This took me sometime to get working.  But did it none the less :)

I'm using Laravel too.  In my mainComponent.vue

    <template>
        <div>
            <dialogs-wrapper
                v-bind:tag="'div'"
                v-bind:name="'default'"
                v-bind:transition-name="'fade'"
                class="modal-wrapper"
            ></dialogs-wrapper>
        </div>
    </template>

    import * as ModalDialogs from 'vue-modal-dialogs';

    Vue.use(ModalDialogs);

    <style>
    .dialog-mask {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-align: center;
        align-items: center;
        -ms-flex-pack: center;
        justify-content: center;
        background-color: rgba(0,0,0,.33);
        z-index: 999991;
    }
    </style>

In the component which calls the dialog

    <script>
    import { create } from 'vue-modal-dialogs';
    import MessageComponent from './message.vue';

    // Make a dialog function called 'message' with two arguments: 'title' and 'content'
    const message = create(MessageComponent, 'title', 'content')

    export default {
        name: 'Foo',
        data () {
            return {
            }
        },
        methods: {
            removeEverything () {
                message('Warning', 'Are you sure to remove everything from your computer?')
            }
        }
    }
    </script>

The MessageComponent inside the dialogue

	<template>
		<div class="message-box dialog-mask">
			<div class="dialog-content">
				<header>{{ title }}</header>
				<div class="dialog-body">
					<p>{{ content }}</p>
				</div>
				<footer>
					<button class="el-button" @click="$close(true)">confirm</button>
					<button class="el-button" @click="cancel">cancel</button>
				</footer>
			</div>
		</div>
	</template>

	<script>
	export default {
		methods: {
			cancel () {
				this.$close(false)
		  	}
		}
	}
	</script>

	<style>
	.dialog-content header {
		margin: 10px 0 26px;
		font-size: 18px;
		font-weight: 700;
	}
	.dialog-content {
		margin: 0 20px;
		padding: 20px 30px;
		border: 1px solid #ebeef5;
		border-radius: 4px;
		background-color: #fff;
		box-shadow: 0 2px 12px 0 rgba(0,0,0,.1);
		color: #303133;
	}
	.dialog-content footer {
		display: -ms-flexbox;
		display: flex;
		margin-top: 24px;
	}
	.dialog-content .el-button {
		-ms-flex: 1;
		flex: 1;
		border: 0;
		color: #409eff;
		-webkit-appearance: none;
		-moz-appearance: none;
		appearance: none;
	}
	.message-box .dialog-content {
		min-width: 240px;
		text-align: center;
		font-size: 16px;
	}
	</style>

Thanks for making the component!

**Comment by hjkcai** [comment]
@paulm17 Could you please host a running example somewhere and its source code?
