### ISSUE TITLE
Move development dependencies to devDependencies in package.json

### ISSUE THREAD

**Issue by Mike-Gibson-Advanced** [hjkcai/vue-modal-dialogs#2]
I noticed when I installed vue-modal-dialogs, that it pulled `babel-preset-env` and `element-ui` into the project too. It seems that these are actually dev dependencies and can be moved in package.json to the `devDependencies` section.

Happy to create a PR if you like?

**Comment by hjkcai** [comment]
Sure! `element-ui` is actually an unused dependency I forgot to remove ☹️. That is my mistake. Thanks for helping me solving dependency problems.
