### ISSUE TITLE
Port to Vue 3 (vue-next)

### ISSUE THREAD

**Issue by theovier** [hjkcai/vue-modal-dialogs#24]
Hey,

thanks for this plugin. I was wondering if there are any plans on porting this project to Vue3?

Cheers.

**Comment by hjkcai** [comment]
Sorry for the late reply. Currently I have no plan to migrate this project to Vue 3 before Vue 3 is stable. Contribution is welcomed!

**Comment by Troyhy** [comment]
Vue3 has [Teleport](https://v3.vuejs.org/guide/teleport.html#teleport) feature that could siplify plugin...

**Comment by githendrik** [comment]
any updates? vue3 has been stable for a while now :-)

**Comment by harmyderoman** [comment]
Guys, I'm working on my own library inspired by this great project. It works on Vue 3. But I used new Composition API and some hooks. I want to provide the same functionality as this project but in new way, using new futures that Vue 3 bring us. Please check this one and say what you think. https://github.com/harmyderoman/vuejs-confirm-dialog

**Comment by rlemaigre** [comment]
Hello,

Not a genuine port to Vue 3, but the basic functionality is there : https://github.com/rlemaigre/vue3-promise-dialog

Have fun !

**Comment by hjkcai** [comment]
@rlemaigre Thanks a lot! I have pasted your work on README. This repo will be archived.
