### ISSUE TITLE
Method "$error" conflicts with an existing Vue instance method.... 

### ISSUE THREAD

**Issue by lincolnlemos** [hjkcai/vue-modal-dialogs#25]
I'm getting the message below...

`[Vue warn]: Method "$error" conflicts with an existing Vue instance method. Avoid defining component methods that start with _ or $`

Any ideas on why? I don't have any other $error variable at my entire code

**Comment by hjkcai** [comment]
Do you have any globally applied mixin that adds `$error` method into Vue instances?

**Comment by lincolnlemos** [comment]
@hjkcai sorry the delay, looks like I have, below is the code that shows when I use $error on template

`
function error(props) {
  var config = (0, _extends3['default'])({
    type: 'error',
    icon: function icon(h) {
      return h(_icon2['default'], {
        attrs: { type: 'close-circle' }
      });
    },
    okCancel: false
  }, props);
  return (0, _confirm2['default'])(config);
}
`

I believe is something from the package ant-design-vue

**Comment by hjkcai** [comment]
vue-modal-dialogs is driven internally by Vue's event system. You can use the following code as a replacement for `$error`. It may looks hacky but should work.

```js
this.$emit('vue-modal-dialogs:error', error)
```
