### ISSUE TITLE
how to prevent the dialog closing by outside clicking?

### ISSUE THREAD

**Issue by Zakharen** [hjkcai/vue-modal-dialogs#26]
hi to all, could somebody clarify how can I avoid a dialog closing event by clicking outside it?
The idea is to close the dialog only by the form's button.
thank you

**Comment by hjkcai** [comment]
It is all up to you. vue-modal-dialogs is an utility library to promisify dialog-like user interactions. Thus all behaviors are programmable.

Simply remove the call to `$close` function when clicking outside the dialog.
