### ISSUE TITLE
TypeScript compilation error with strictNullChecks = true

### ISSUE THREAD

**Issue by Mike-Gibson-Advanced** [hjkcai/vue-modal-dialogs#3]
Compiling with strict `"strictNullChecks": true` (or `"strict": true` since TypeScript 2.3) causes a compilation error in the typings file:

```
'Interface 'WrapperRenderOptions' incorrectly extends interface 'VNodeData'.
  Types of property 'on' are incompatible.
    Type '{ beforeEnter?: TransitionEventHandler | undefined; enter?: TransitionEventHandler | undefined; a...' is not assignable to type '{ [key: string]: Function | Function[]; } | undefined'.
      Type '{ beforeEnter?: TransitionEventHandler | undefined; enter?: TransitionEventHandler | undefined; a...' is not assignable to type '{ [key: string]: Function | Function[]; } | undefined'.
        Type '{ beforeEnter?: TransitionEventHandler | undefined; enter?: TransitionEventHandler | undefined; a...' is not assignable to type '{ [key: string]: Function | Function[]; }'.
          Property 'beforeEnter' is incompatible with index signature.
            Type 'TransitionEventHandler | undefined' is not assignable to type 'Function | Function[]'.
              Type 'undefined' is not assignable to type 'Function | Function[]'.'
```

It's because `Vue.VNodeData` specifies `on` must be of type `{ [key: string]: Function | Function[] }`. With strict null checks, this means it cannot be undefined, which, for example, `beforeEnter?: TransitionEventHandler` (which is equivalent to `beforeEnter: TransitionEventHandler | undefined`) is specifying.

I like the fact that you get type safety when specifying the wrapper render options - it's useful for a developer. There's a way to solve the issue - to keep typings for the `on` events and satisfy the TypeScript compiler without changing the core vue typings. It's possible to have an intermediate type which widens the `on` property, so
```
interface VNodeData extends Vue.VNodeData {
  on?: any
}
```
and then have `WrapperRenderOptions` extend this new interface.

Happy to put together a PR.

**Comment by hjkcai** [comment]
Hmm.. Please create a single PR (not contain modifications to `package.json`) for this issue. I will examine the definition file again carefully. Sorry for your inconvenience.

**Comment by hjkcai** [comment]
Now `Vue.VNodeData` is used instead of `WrapperRenderOptions`. I think it might be better not to predefine these properties or events because I am not so sure about it, and Vue may change them at any time.

Please install `vue-modal-dialogs@1.1.2` to receive this update.
