### ISSUE TITLE
Can you remove this throw?

### ISSUE THREAD

**Issue by codegor** [hjkcai/vue-modal-dialogs#30]
https://github.com/hjkcai/vue-modal-dialogs/blob/46c45d79665794e34b97be026f4f038ece2d7063/src/wrapper.js#L98

**Comment by codegor** [comment]
or how I can prevent this console message? https://i.imgur.com/84iIR6s.png

**Comment by codegor** [comment]
or disable it for production mode

**Comment by hjkcai** [comment]
Sorry for the late reply. Just use `$close` instead of `$error` in the dialog component. Or catch the error when calling the dialog function.

Please also read about the full usage of JavaScript Promises 😄
